namespace TradingSystem.Core.Models;

/// <summary>
/// Represents a trading signal generated by a strategy
/// </summary>
public class Signal
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    
    // Source
    public string StrategyId { get; set; } = string.Empty;
    public string StrategyName { get; set; } = string.Empty;
    public string SetupType { get; set; } = string.Empty;
    
    // Target security
    public string Symbol { get; set; } = string.Empty;
    public string SecurityType { get; set; } = "STK";
    
    // Signal details
    public SignalDirection Direction { get; set; }
    public SignalStrength Strength { get; set; }
    public decimal? SuggestedEntryPrice { get; set; }
    public decimal? SuggestedStopPrice { get; set; }
    public decimal? SuggestedTargetPrice { get; set; }
    
    // Position sizing guidance
    public decimal? SuggestedPositionSize { get; set; } // In shares/contracts
    public decimal? SuggestedRiskAmount { get; set; } // In dollars
    public decimal? ExpectedRMultiple { get; set; }
    
    // Options-specific (single leg)
    public decimal? SuggestedStrike { get; set; }
    public DateTime? SuggestedExpiration { get; set; }
    public OptionRight? SuggestedRight { get; set; }

    // Options-specific (multi-leg strategies)
    public List<OptionLeg>? SuggestedLegs { get; set; }
    public decimal? MaxProfit { get; set; }
    public decimal? MaxLoss { get; set; }
    public decimal? ProbabilityOfProfit { get; set; }
    public decimal? IVRank { get; set; }
    public decimal? IVPercentile { get; set; }
    
    // Context
    public string Rationale { get; set; } = string.Empty;
    public Dictionary<string, object> Indicators { get; set; } = new(); // RSI, ATR, etc.
    public List<string> QualityGatesPassed { get; set; } = new();
    public List<string> QualityGatesFailed { get; set; } = new();
    
    // Validity
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    public DateTime ExpiresAt { get; set; }
    public bool IsValid => DateTime.UtcNow < ExpiresAt && Status == SignalStatus.Active;
    public SignalStatus Status { get; set; } = SignalStatus.Active;
    
    // Execution tracking
    public bool WasExecuted { get; set; }
    public string? ExecutedOrderId { get; set; }
    public string? ExecutionNotes { get; set; }
}

public enum SignalDirection
{
    Long,
    Short,
    ClosePosition,
    ReducePosition,
    Hold
}

public enum SignalStrength
{
    Weak,
    Moderate,
    Strong,
    VeryStrong
}

public enum SignalStatus
{
    Active,
    Executed,
    Expired,
    Cancelled,
    Rejected // Failed risk checks
}
